### ISSUE TITLE
Pdf to text too slow

### ISSUE THREAD

**Issue by vinhbui1** [thevikke/read_pdf_text#6]
It takes me more than 2 minute for 100 pages in pdf. Can we improve it?
I see pdf to text in android vert fast, where is the problem ?

**Comment by thevikke** [comment]
Do you mean that it is slow on iOS, but faster on Android?

**Comment by vinhbui1** [comment]
No . it slow on Flutter , It faster in Android Navite (Not Flutter)

**Comment by thevikke** [comment]
This package uses Pdfbox plugin on Android. I was not aware there is native Android API for parsing PDF documents. What is it called?

**Comment by vinhbui1** [comment]
I mean, I found an app in ChPlay very fast when converting Pdf to text offline. (The same PDF file I used in your library took me 2 minutes, but in this app only takes 5s)  Can we investigate it?
https://play.google.com/store/apps/details?id=com.hyperionics.avar&hl=vi&gl=US

**Comment by thevikke** [comment]
Well sure, you can investigate it. If you find something faster let me know or create a PR.

**Comment by thevikke** [comment]
Seems to me that application is also using PdfBox paclage for parsing. So it is the same package as we use.

**Comment by thevikke** [comment]
I guess you can clone the repo. Check the Android code for performance improvements, or you can try upgrading the PdfBox version: implementation 'com.tom-roush:pdfbox-android:2.0.25.0'. From https://github.com/TomRoush/PdfBox-Android.

**Comment by thevikke** [comment]
We are running the Pdfbox parser in a isolate, so that it doesn't lock the UI thread during PDF-parsing. However, I'm no Android developer so there might be performance improvements to be made.

I may have some time next week to look into this issue. If you are not able to?

**Comment by vinhbui1** [comment]
Pls, help me take a look. Thanks

**Comment by thevikke** [comment]
UPDATE: 

Well I did some research with a 144 pages long pdf document. I tested the aforementioned @Voice Aloud Reader, which parsed the text from the document in around 34 seconds. Our package in debug mode parsed the same document in 2:05. Which is about a minute and a half longer. If running with release mode the time drops to around 1:30, which is better but still far from the Aloud Reader. All tests were ran on same device.

Now I do not know why this is happening, since @Voice Aloud Reader and this package use the same Android PdfBox library to parse the text. Maybe Flutter creates some friction, I don't know. Maybe there is some optimization to be done with the Android code of this package. The only advice I can give at this point is, that running Flutter in release mode significantly speeds up the parsing process (25%).

I will do some refactoring to try improve the performance in near future, but that might take awhile, since I also work and study at the same time. So don't hold your breath.
